### PR TITLE
home town information

### PR DESCRIPTION
**Pull request by arturom-uci**
this feature contains changes to add my hometown info.

### CODE REVIEW

**Comment by arturom-uci** [comment]
@grodrigu @jellesse92 can you look at this?

**Comment by grodrigu** [comment]
Looks incomplete, but we don't have time to fix it

**Comment by arturom-uci** [comment]
will leave as is for now & merge.

**Comment by arturom-uci** [comment]
@grodrigu i meant to say.... thx for merging for me.

**Comment by grodrigu** [comment]
Stole your thunder and committed

**Pull request merged**
